### ISSUE TITLE
impfdashboard.de

### ISSUE THREAD

**Issue by fossdd** [ard-data/2020-rki-impf-archive#12]
Ich wollte nur mal hiermit anmerken, dass das Bundesministerium fuer Gesundheit Impf-Daten zusaetzlich als CSV verfuegbar stellt

https://impfdashboard.de/daten

Ich weiß nicht ob die einfach das gleiche machen und die Daten in TSV liefern, oder ob es eine "extra" Quelle ist.

**Comment by MichaelKreil** [comment]
Danke für den Hinweis.
Leider helfen diese Daten nicht dabei, z.B. Zeitreihen für einzelne Bundesländer und Vakzine zu erstellen.
Aber ich hab das mal zum Anlass genommen, den entsprechenden Absatz in der README zu aktualisieren: https://github.com/ard-data/2020-rki-impf-archive/commit/ef3e6af063fe314fdb90f4306b814c545cf60be8
