### ISSUE TITLE
RKI changed table columns :-/

### ISSUE THREAD

**Issue by edg-stg** [ard-data/2020-rki-impf-archive#14]
Änderung der Tabelle zum Digitalen Impfquotenmonitoring ab Montag, 7.6.2021

1.) Die Impfquote nach Alter wird in 3 Gruppen ausgewiesen (<18 Jahre, 18-59 Jahre und 60+ Jahre).
2.) Es werden "mindestens einmal Geimpfte" und "vollständig Geimpfte" aufgeführt (zu beachten: Personen, die mit dem COVID-19 Vaccine Janssen von Janssen-Cilag International geimpft wurden, sind in beiden Kategorien aufgeführt).
3.) Impfungen werden nicht mehr nach Impfstelle (Impfzentren/mobile Teams/Krankenhäuser und Niedergelassene Ärzteschaft) ausgewiesen. Über Impfungen nach Impfstelle soll wöchentlich gesondert berichtet werden.

**Comment by MichaelKreil** [comment]
Arbeite bereits unter Hochdruck daran. :)

**Comment by MichaelKreil** [comment]
zu 1.) Habe ich entsprechend hinzugefügt.
zu 2.) Ist jetzt so gelöst: https://github.com/ard-data/2020-rki-impf-archive#erstimpfung-zweitimpfung-volle-impfung-
Ist das verständlich so oder könnte man das besser machen?
zu 3.) Die entsprechenden Werte werden also erstmal nicht aktualisiert.
Aufgrund der Veränderungen auch an der CSV-Struktur, liegen die Daten jetzt im Verzeichnis: data/9_csv_v3
https://ard-data.github.io/2020-rki-impf-archive/data/9_csv_v3/

**Comment by edg-stg** [comment]
vielen dank! 
werden die impfquoten für die unter-18-jährigen auch ins csv aufgenommen?

**Comment by MichaelKreil** [comment]
Klaro ... ich darf es nur nicht vergessen zu aktivieren. *hust*
Es gibt jetzt die Parameter:
- impf_quote_min1_alter_unter18 und
- impf_quote_voll_alter_unter18
