### ISSUE TITLE
Impfquote Alter 5-11

### ISSUE THREAD

**Issue by edg-stg** [ard-data/2020-rki-impf-archive#15]
Leider ist die Impfquote für die (neue) Altersgruppe 5-11 immer NA, die kumulierte Zahl der Impfungen dieser AG ist aber da.

**Comment by MichaelKreil** [comment]
Das Ziel dieses Projektes ist es, die Zahlen der RKI-Exceltabellen so neutral wie möglich in CSV zu konvertieren. Dabei sollen im Idealfall keine zusätzlichen Berechnungen durchgeführt werden, die Annahmen voraussetzen. Andernfalls besteht die Gefahr, dass die hier veröffentlichten Zahlen mit den Zahlen des RKI auseinanderlaufen.

Beispiel: Für die Berechnung der Impfquote der 5-11-Jährigen benötigen wir die Anzahl der 5-11-Jährigen je Bundesland. Diese Zahlen werden jährlich veröffentlicht, aber ändern sich auch jährlich. Das sorgt für künstliche Sprünge in einer berechneten Impfquote. Man könnte deshalb ein Jahr auswählen, dessen Bevölkerungszahlen man als Grundlage für alle Impfquoten-Berechnungen verwendet. Es ist aber nicht klar, welches Jahr das sein könnte. Falls das RKI nachträglich die Impfquote für 5-11-Jährigen veröffentlichen sollte, besteht die Gefahr, dass die hier veröffentlichten, selbst berechneten Impfquoten mit denen vom RKI abweichen.

Deshalb: Dieses Projekt will die RKI-Zahlen ganz neutral und 1:1 in ein anderes Format umwandeln. Alle zusätzlichen Berechnungen und Annahmen erhöhen die Gefahr, Zahlen zu veröffentlichen, die von den offiziellen Zahlen abweichen. Solange das RKI in den Exceltabellen keine "Impfquote der 5-11-Jährigen" veröffentlicht, würden wir das im Rahmen dieses Projektes auch nicht tun.

Ein anderer Aspekt ihrer Frage ist, dass viele Felder/Spalten in den CSV-Dateien leer sind. Mich stört das ästhetisch auch. Würde es helfen, wenn bei der Generierung der CSV-Dateien leere Felder/Spalten rausgefiltert werden?

**Comment by MichaelKreil** [comment]
... und ich sehe gerade, dass das RKI angekündigt hat, ab dem 18.1.2022 u.a. die "Impfquoten für die 5-11-Jährigen" auszuweisen.

**Comment by edg-stg** [comment]
impfquote ist da.
