### ISSUE TITLE
Plausibilitätchecks

### ISSUE THREAD

**Issue by MichaelKreil** [ard-data/2020-rki-impf-archive#3]
Z.B.
- kumulativwert - differenz === vortageswert
- gesamtwert_history === gesamtwert_tagesstand
- erstimpfung + zweitimpfung === gesamtwert

**Comment by stegers** [comment]
Wie wir bereits vermutet hatten:  In den Anmerkungen den RKI heißt es _Nachmeldungen aus zurückliegenden Tagen werden rückwirkend für den jeweiligen Impftag nachgetragen._

Diese tauchen Dokument Impfquotenmonitoring dann also tauchen dann also nur Korrektur in _Impfungen_proTag / Gesamtzahl_Impfungen_ auf bzw. bestenfalls indirekt als korrigierter Vortagswert, aber das Nachmeldungen an länger zurückliegenden Tagen in einzelnen Bundesländern sind nicht ersichtlich.

**Comment by yetzt** [comment]
nachmeldungen erklären nicht weshalb die differenz der zweiten impfungen im aktuellen sheet unter **Impfungen_proTag** `13252` (*C24*) beträgt, unter **Gesamt_bis_einschl_18.01.21** jedoch `12594` (*J20*)

**Comment by MichaelKreil** [comment]
Ich habe mal die Meldungen für den 27-12-2020 aus allen Tabellen extrahiert. Man sieht, dass mit fortlaufendem Datum die Nachmeldungen eintrudeln. Bis heute sind die Meldungen für diesen einen Tag um 12% gestiegen.
https://gist.github.com/MichaelKreil/f33e9b8d9e8c56b3364b374b41cae95f

**Comment by MichaelKreil** [comment]
Ok, jetzt sind zahlreiche Plausibilitätschecks drin.
Ich definiere die Daten als Datenwürfel: https://github.com/ard-data/2020-rki-impf-archive/blob/master/config/data_definition.js
Jeder Feldname wird (Vorlage war das Impf-Dashboard) automatisch generiert: https://github.com/ard-data/2020-rki-impf-archive/blob/88afe0761fec56e493fea5066174e357bb49c2ad/config/data_definition.js#L88
Auf dieser Basis kann ich nun Plausibilitätschecks definieren: https://github.com/ard-data/2020-rki-impf-archive/blob/88afe0761fec56e493fea5066174e357bb49c2ad/bin/4_complete_data.js#L140
Falls das RKI sie nicht einhalten kann, müssen sie manuell "toleriert" werden: https://github.com/ard-data/2020-rki-impf-archive/blob/master/config/known_problems.csv

Damit sind jetzt mehr Checks drin, als gefordert.
Das einzige, was noch fehlt, sind Checks, ob die Summen für Bundesländer aufgehen. Das habe ich in ein separates Issue ausgelagert: https://github.com/ard-data/2020-rki-impf-archive/issues/10
