### ISSUE TITLE
Impfstoffunterscheidung

### ISSUE THREAD

**Issue by stegers** [ard-data/2020-rki-impf-archive#4]
Hast du diese Datei schon auf dem Schirm? Nur Daten auf Bundesebene, aber dafür mit Unterscheidung nach Impfstoff.

https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv
via: https://impfdashboard.de/

**Comment by MichaelKreil** [comment]
Ja, die Daten werden bereits extrahiert und liegen in den JSONs vor. Es gibt aber noch kein CSV-Export dazu.
Vorher schaue ich mir aber das Dashboard genauer an. Interessante Datenquelle!
