### ISSUE TITLE
all.json oder all.csv auch mit Zweitimpfung

### ISSUE THREAD

**Issue by edg-stg** [ard-data/2020-rki-impf-archive#7]
Das aggregierte csv-File ist sehr nützlich. Es wäre super, wenn dort auch die Zweitimpfungen erfasst würden. Alternativ auch in einem aggregierten all.json.

**Comment by MichaelKreil** [comment]
Vorschlag: Ich würde alle CSV-Dateien so anpassen, so dass die Felder genauso heißen, wie im Impfdashboard. Ich glaube, die haben alle relevanten Zahlen drin und haben die Felder auch sinnvoll benannt:
https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv

Die neuen Feldnamen wären dann:
- date
- dosen_kumulativ
- dosen_differenz_zum_vortag
- dosen_biontech_kumulativ
- dosen_moderna_kumulativ
- personen_erst_kumulativ
- personen_voll_kumulativ
- impf_quote_erst
- impf_quote_voll
- indikation_alter_dosen
- indikation_beruf_dosen
- indikation_medizinisch_dosen
- indikation_pflegeheim_dosen
- indikation_alter_erst
- indikation_beruf_erst
- indikation_medizinisch_erst
- indikation_pflegeheim_erst
- indikation_alter_voll
- indikation_beruf_voll
- indikation_medizinisch_voll
- indikation_pflegeheim_voll

**Comment by MichaelKreil** [comment]
Hm, das geht nicht, denn das RKI schlüsselt die Impfdosen nur für die Erstimpfung nach Herstellern auf. Die Zweitimpfungen werden nicht aufgeschlüsselt. Aus meiner Perspektive lässt sich die Aufschlüsselung der Zweitimpfung auch nicht nachträglich berechnen.
Ich frage mal beim RKI nach.

**Comment by edg-stg** [comment]
Ich denke, da im Moment nur Biontech zweitverimpft wird, unterscheidet das RKI danach noch nicht. Aber sie werden bestimmt in zwei Wochen neue Spalten in die Tabelle einfügen 😉

**Comment by untergeekDE** [comment]
Relativ einfach: Man kann die Impfstoffe per Definition und laut Zulassung nicht mischen. Wer Moderna bekommen hat, braucht nochmal Moderna. Ohnehin ist ja die deutsche Praxis so, dass jede Lieferung geteilt und die Hälfte für die Zweitimpfung eingelagert wird. 

Erstimpfung nach Impfstoff reicht also. :)

Ich bin mit den neuen Feldnahmen ein wenig hin- und hergerissen. Für die Einzelfiles der Länder wäre es (auch für eine Zeitserie) m.E. einfacher, die bisher fehlenden Feldnamen als zusätzliche Spalten einzuführen. (Und ja: dass die nachträglichen Korrekturen nicht drin sind, ist ein Problem, aber das kennen wir ja.)

**Comment by MichaelKreil** [comment]
Ist gefixt:
JSON pro Tag: https://github.com/ard-data/2020-rki-impf-archive/tree/master/data/2_completed
CSV für alles: https://github.com/ard-data/2020-rki-impf-archive/tree/master/data/9_csv_v2
